version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: trailnetwork
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  trailnetwork:
    build: ./TrailNetwork
    container_name: trailnetwork
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/trailnetwork

volumes:
  mongodb-data:
